name: Pull request content check.
description: Block merging unless the Pull Request matches the configured patterns.
inputs:
  github_token:
    description: 'Github OAuth2 token'
    required: true
  body_pattern:
    description: 'Regular expression pattern to check for in the Pull Request body.'
    required: false
  title_pattern:
    description: 'Regular expression pattern to check for in the Pull Request title.'
    required: false
  success_message:
    description: 'Message to emit on success.'
    required: true
  failure_message:
    description: 'Message to emit on failure.'
    required: true
runs:
  using: 'node16'
  main: 'index.js'
